### ISSUE TITLE
A11y: on:mouseover must be accompanied by on:focus with Svelte v3.44

### ISSUE THREAD

**Issue by Kiho** [metonym/svelte-spectrum-icons#20]
I updated to Svelte v3.44 then get warnings on build.

**Comment by metonym** [comment]
Could you assist with providing a repro?

Each icon generated by this library has `<!-- svelte-ignore a11y-mouse-events-have-key-events -->` prepended to the source.

The [Svelte REPL example](https://svelte.dev/repl/8b2c2ef9ad68426bb320d455026b666e?version=3.44.1) uses Svelte v3.44.1, and no a11y warnings are logged in the console.

**Comment by Kiho** [comment]
Sorry, it was my mistake, my project was referencing 2.0.0.
I don't see any issues with 2.1.0
